version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 125736546
      POSTGRES_DB: retail_company_bi_platform_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:125736546@db/retail_company_bi_platform_db
    depends_on:
      - db
    networks:
      - backend_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
